import { buildAllFranchiseRankings, type FranchiseRankingIndustryConfig } from "../build-franchise-rankings";

const sources = [
  "Franchise Disclosure Document (FDD) Item 5–7 ranges (brand systems)",
  "BizMetricsHQ massage franchise operator panel (directional)",
  "Public franchise directories and unit-count disclosures",
  "U.S. wellness / day spa industry benchmarks 2025–2026",
] as const;

const config: FranchiseRankingIndustryConfig = {
  industryKey: "massage",
  industryLabel: "Massage",
  industryLabelPlural: "Massage Studios",
  noun: "massage",
  guideHref: "/franchise/beauty/massage/",
  rankingsBaseHref: "/franchise/beauty/massage/rankings/",
  sources,
  anchors: {
    investmentRange: "$250K – $600K",
    medianInvestment: "$400K",
    franchiseFee: "$30K – $55K",
    royaltyCombined: "7 – 9%",
    unitRevenue: "$500K – $1.2M",
    medianRevenue: "$750K",
    netMarginAfterFees: "8 – 15%",
    ebitda: "10 – 20%",
    ownerIncomeSingle: "$60K – $130K",
    payback: "3 – 5 years",
  },
  calculators: [
    { label: "Day Spa Startup Cost Calculator", href: "/calculators/day-spa-startup-cost/" },
    { label: "Day Spa Profit Margin Calculator", href: "/calculators/day-spa-profit-margin/" },
    { label: "Day Spa Break-even Calculator", href: "/calculators/day-spa-break-even/" },
  ],
  compareHref: "/comparisons/day-spa-vs-massage-spa/",
  keywords: {
    best: ["best massage franchises", "best massage franchise to buy", "top massage franchise opportunities"],
    "lowest-cost": ["lowest cost massage franchise", "cheapest massage franchise", "massage franchise under 300k"],
    "highest-revenue": ["highest revenue massage franchise", "how much does a massage franchise make", "massage envy average revenue"],
    "fastest-growing": ["fastest growing massage franchises", "massage franchise expansion 2026", "growing massage studio franchises"],
    "first-time": ["best massage franchise for first-time owners", "massage franchise for beginners", "massage franchise no experience"],
    "most-profitable": ["most profitable massage franchise", "highest ROI massage franchise", "massage franchise profit margin"],
  },
  brands: [
    {
      name: "Massage Envy",
      investment: "$400K – $600K",
      fee: "$45K – $55K",
      royalty: "6% + ads",
      units: "1,000+",
      revenue: "$700K – $1.2M",
      netMargin: "9 – 15%",
      growth: "High",
      firstTimerFit: "Strong",
      notes: "Largest footprint; membership volume model",
      costRank: 5,
      revenueRank: 1,
      growthRank: 1,
      firstTimerRank: 2,
      profitRank: 2,
      bestRank: 1,
      buyerFit: "Multi-unit membership operators",
    },
    {
      name: "Elements Massage",
      investment: "$300K – $500K",
      fee: "$40K – $50K",
      royalty: "6% + ads",
      units: "250+",
      revenue: "$550K – $950K",
      netMargin: "10 – 16%",
      growth: "High",
      firstTimerFit: "Excellent",
      notes: "Boutique therapist culture; strong training depth",
      costRank: 3,
      revenueRank: 4,
      growthRank: 3,
      firstTimerRank: 1,
      profitRank: 1,
      bestRank: 2,
      buyerFit: "First-time & boutique buyers",
    },
    {
      name: "Hand & Stone",
      investment: "$350K – $550K",
      fee: "$40K – $50K",
      royalty: "6% + ads",
      units: "500+",
      revenue: "$600K – $1.1M",
      netMargin: "9 – 15%",
      growth: "High",
      firstTimerFit: "Strong",
      notes: "Massage + facial combo expands ticket",
      costRank: 4,
      revenueRank: 2,
      growthRank: 2,
      firstTimerRank: 3,
      profitRank: 3,
      bestRank: 3,
      buyerFit: "Combo wellness operators",
    },
    {
      name: "LaVida Massage",
      investment: "$250K – $450K",
      fee: "$30K – $45K",
      royalty: "5–6% + ads",
      units: "100+",
      revenue: "$450K – $800K",
      netMargin: "8 – 14%",
      growth: "Moderate",
      firstTimerFit: "Good",
      notes: "Often lowest CapEx band among national concepts",
      costRank: 1,
      revenueRank: 6,
      growthRank: 5,
      firstTimerRank: 4,
      profitRank: 4,
      bestRank: 4,
      buyerFit: "Capital-constrained buyers",
    },
    {
      name: "Massage Heights",
      investment: "$300K – $500K",
      fee: "$35K – $45K",
      royalty: "6% + ads",
      units: "150+",
      revenue: "$500K – $900K",
      netMargin: "8 – 14%",
      growth: "Moderate",
      firstTimerFit: "Good",
      notes: "Membership + retail mix in suburban plazas",
      costRank: 2,
      revenueRank: 5,
      growthRank: 4,
      firstTimerRank: 5,
      profitRank: 5,
      bestRank: 5,
      buyerFit: "Suburban membership studios",
    },
    {
      name: "The Woodhouse Spa",
      investment: "$500K – $900K+",
      fee: "$45K – $65K",
      royalty: "6% + ads",
      units: "70+",
      revenue: "$800K – $1.5M+",
      netMargin: "8 – 14%",
      growth: "Selective",
      firstTimerFit: "Moderate",
      notes: "Premium hybrid spa; highest CapEx and ticket",
      costRank: 6,
      revenueRank: 3,
      growthRank: 6,
      firstTimerRank: 6,
      profitRank: 6,
      bestRank: 6,
      buyerFit: "Premium spa operators",
    },
  ],
};

const built = buildAllFranchiseRankings(config);

export const massageFranchiseRankings = built.bySlug;
export const massageFranchiseRankingSlugs = built.slugs;
export const massageFranchiseRankingCards = built.cards;
