import { buildAllFranchiseRankings, type FranchiseRankingIndustryConfig } from "../build-franchise-rankings";

const sources = [
  "Franchise Disclosure Document (FDD) Item 5–7 ranges (brand systems)",
  "BizMetricsHQ waxing franchise operator panel (directional)",
  "Public franchise directories and unit-count disclosures",
  "U.S. beauty / personal care industry benchmarks 2025–2026",
] as const;

const config: FranchiseRankingIndustryConfig = {
  industryKey: "waxing",
  industryLabel: "Waxing",
  industryLabelPlural: "Waxing Studios",
  noun: "waxing",
  guideHref: "/franchise/beauty/waxing/",
  rankingsBaseHref: "/franchise/beauty/waxing/rankings/",
  sources,
  anchors: {
    investmentRange: "$200K – $500K",
    medianInvestment: "$325K",
    franchiseFee: "$25K – $60K",
    royaltyCombined: "7 – 9%",
    unitRevenue: "$350K – $900K",
    medianRevenue: "$550K",
    netMarginAfterFees: "8 – 16%",
    ebitda: "10 – 22%",
    ownerIncomeSingle: "$55K – $120K",
    payback: "3 – 5 years",
  },
  calculators: [
    { label: "Day Spa Startup Cost Calculator", href: "/calculators/day-spa-startup-cost/" },
    { label: "Day Spa Profit Margin Calculator", href: "/calculators/day-spa-profit-margin/" },
    { label: "Day Spa Valuation Calculator", href: "/calculators/day-spa-valuation/" },
  ],
  compareHref: "/comparisons/nail-salon-vs-waxing-salon/",
  keywords: {
    best: ["best waxing franchises", "best wax franchise to buy", "top waxing franchise opportunities"],
    "lowest-cost": ["lowest cost waxing franchise", "cheapest wax franchise", "waxing franchise under 250k"],
    "highest-revenue": ["highest revenue waxing franchise", "how much does a european wax center make", "wax franchise average sales"],
    "fastest-growing": ["fastest growing waxing franchises", "wax franchise expansion 2026", "growing wax studio franchises"],
    "first-time": ["best waxing franchise for first-time owners", "wax franchise for beginners", "waxing franchise no experience"],
    "most-profitable": ["most profitable waxing franchise", "highest ROI wax franchise", "waxing franchise profit margin"],
  },
  brands: [
    {
      name: "European Wax Center",
      investment: "$350K – $500K",
      fee: "$45K – $60K",
      royalty: "6% + ads",
      units: "900+",
      revenue: "$500K – $900K",
      netMargin: "10 – 16%",
      growth: "High",
      firstTimerFit: "Strong",
      notes: "Largest soft-wax footprint; membership frequency model",
      costRank: 5,
      revenueRank: 1,
      growthRank: 1,
      firstTimerRank: 2,
      profitRank: 1,
      bestRank: 1,
      buyerFit: "Multi-unit membership operators",
    },
    {
      name: "Waxing the City",
      investment: "$250K – $420K",
      fee: "$40K – $50K",
      royalty: "6% + ads",
      units: "150+",
      revenue: "$400K – $750K",
      netMargin: "10 – 16%",
      growth: "High",
      firstTimerFit: "Excellent",
      notes: "Boutique wax studios; strong training for new owners",
      costRank: 3,
      revenueRank: 3,
      growthRank: 2,
      firstTimerRank: 1,
      profitRank: 2,
      bestRank: 2,
      buyerFit: "First-time boutique buyers",
    },
    {
      name: "The Waxing Company",
      investment: "$200K – $380K",
      fee: "$30K – $45K",
      royalty: "5–6% + ads",
      units: "Growing",
      revenue: "$350K – $650K",
      netMargin: "9 – 15%",
      growth: "Moderate",
      firstTimerFit: "Good",
      notes: "Lower CapEx entry in many markets",
      costRank: 2,
      revenueRank: 5,
      growthRank: 4,
      firstTimerRank: 4,
      profitRank: 3,
      bestRank: 3,
      buyerFit: "Capital-constrained markets",
    },
    {
      name: "Sugar Sugar",
      investment: "$220K – $400K",
      fee: "$35K – $45K",
      royalty: "6% + ads",
      units: "Growing",
      revenue: "$380K – $700K",
      netMargin: "9 – 15%",
      growth: "High",
      firstTimerFit: "Good",
      notes: "Sugaring specialty differentiation",
      costRank: 4,
      revenueRank: 4,
      growthRank: 3,
      firstTimerRank: 5,
      profitRank: 4,
      bestRank: 4,
      buyerFit: "Specialty hair-removal",
    },
    {
      name: "Brow / Express formats",
      investment: "$180K – $350K",
      fee: "$25K – $40K",
      royalty: "5–6% + ads",
      units: "Varies",
      revenue: "$300K – $550K",
      netMargin: "8 – 14%",
      growth: "Moderate",
      firstTimerFit: "Good",
      notes: "Smallest footprints; often lowest investment band",
      costRank: 1,
      revenueRank: 6,
      growthRank: 5,
      firstTimerRank: 3,
      profitRank: 5,
      bestRank: 5,
      buyerFit: "Express beauty add-on",
    },
    {
      name: "Ideal Image (laser)",
      investment: "$500K – $1.1M",
      fee: "$40K – $60K",
      royalty: "6% + ads",
      units: "150+",
      revenue: "$900K – $2.5M",
      netMargin: "8 – 15%",
      growth: "Selective",
      firstTimerFit: "Moderate",
      notes: "Highest revenue hybrid; laser CapEx lifts investment",
      costRank: 6,
      revenueRank: 2,
      growthRank: 6,
      firstTimerRank: 6,
      profitRank: 6,
      bestRank: 6,
      buyerFit: "Laser hair-removal hybrids",
    },
  ],
};

const built = buildAllFranchiseRankings(config);

export const waxingFranchiseRankings = built.bySlug;
export const waxingFranchiseRankingSlugs = built.slugs;
export const waxingFranchiseRankingCards = built.cards;
