import type { FitnessFormatProfile } from "./build-gym-comparison";

export const pilatesStudioProfile: FitnessFormatProfile = {
  label: "Pilates Studio",
  kpis: {
    annualRevenue: "$350K – $900K",
    netMargin: "18 – 28%",
    ownerComp: "$90K – $170K",
    revenuePerMember: "$120 – $220/mo",
    startup: "$80K – $250K",
    valuation: "2.5× – 3.8× SDE",
    recurringPct: "85 – 95% MRR",
  },
  revenueSources: [
    "Monthly Class Memberships",
    "Private Reformer Sessions",
    "Semi-Private Sessions",
    "Workshops & Intensives",
    "Teacher Training Programs",
  ],
  revenueFunnel: ["Lead", "Intro Package", "Membership", "Private Sessions", "Retention", "Revenue"],
  memberFunnel: ["Prospect", "Intro Offer", "Member", "Private Upgrade", "Referral"],
  staffFunnel: ["Instructor", "Class / Session", "Revenue"],
  marginTiers: { weak: "10 – 14%", average: "15 – 20%", strong: "21 – 28%" },
  startupItems: [
    { item: "Reformers & Equipment", percent: 42 },
    { item: "Lease & Buildout", percent: 28 },
    { item: "Marketing Launch", percent: 15 },
    { item: "Working Capital", percent: 15 },
  ],
  startupSideBySide: {
    equipment: "$45K – $120K",
    lease: "$25K – $70K",
    marketing: "$10K – $35K",
    total: "$80K – $250K",
  },
  valuation: {
    sde: "2.5× – 3.8×",
    revenue: "0.5× – 0.9×",
    ebitda: "3.5× – 5.5×",
    example: { revenue: "$650K", value: "$420K – $640K", note: "3.0× SDE on $180K SDE" },
  },
  scalingLadder: ["Single Studio", "150+ Members", "Private Session Mix", "Multi-Studio Brand"],
  capitalEfficiency: {
    revenue: "$500K – $800K",
    profit: "$90K – $180K net profit",
    payback: "2 – 4 years",
  },
  recurringHighlight: {
    title: "Premium Recurring Model",
    value: "85 – 95% membership MRR",
  },
};

export const crossFitProfile: FitnessFormatProfile = {
  label: "CrossFit",
  kpis: {
    annualRevenue: "$400K – $1.1M",
    netMargin: "15 – 25%",
    ownerComp: "$85K – $180K",
    revenuePerMember: "$150 – $250/mo",
    startup: "$100K – $350K",
    valuation: "2.8× – 4.0× SDE",
    recurringPct: "80 – 90% MRR",
  },
  revenueSources: [
    "Unlimited Memberships",
    "Class Pack Sales",
    "Personal Coaching",
    "Nutrition Challenges",
    "Merchandise & Events",
  ],
  revenueFunnel: ["Lead", "Free Intro Class", "Membership", "Community", "Retention", "Revenue"],
  memberFunnel: ["Prospect", "On-Ramp Program", "Member", "Nutrition / PT Add-on", "Referral"],
  staffFunnel: ["Coach", "Class Attendance", "Revenue"],
  marginTiers: { weak: "8 – 12%", average: "13 – 18%", strong: "19 – 25%" },
  startupItems: [
    { item: "Equipment & Rig Buildout", percent: 35 },
    { item: "Lease & Buildout", percent: 25 },
    { item: "Marketing Launch", percent: 20 },
    { item: "Working Capital", percent: 20 },
  ],
  startupSideBySide: {
    equipment: "$50K – $150K",
    lease: "$30K – $90K",
    marketing: "$15K – $50K",
    total: "$100K – $350K",
  },
  valuation: {
    sde: "2.8× – 4.0×",
    revenue: "0.5× – 1.0×",
    ebitda: "3.8× – 5.8×",
    example: { revenue: "$750K", value: "$490K – $760K", note: "3.2× SDE on $200K SDE" },
  },
  scalingLadder: ["Affiliate Box", "120+ Members", "Coach-Led Community", "Multi-Box Operator"],
  capitalEfficiency: {
    revenue: "$600K – $950K",
    profit: "$90K – $190K net profit",
    payback: "3 – 5 years",
  },
  recurringHighlight: {
    title: "Community Retention Model",
    value: "80 – 90% membership MRR",
  },
};

export const yogaStudioProfile: FitnessFormatProfile = {
  label: "Yoga Studio",
  kpis: {
    annualRevenue: "$250K – $700K",
    netMargin: "15 – 25%",
    ownerComp: "$70K – $140K",
    revenuePerMember: "$80 – $160/mo",
    startup: "$50K – $150K",
    valuation: "2.2× – 3.5× SDE",
    recurringPct: "75 – 90% MRR",
  },
  revenueSources: [
    "Monthly Unlimited Memberships",
    "Class Pack Sales",
    "Workshops & Retreats",
    "Teacher Training",
    "Retail & Wellness Products",
  ],
  revenueFunnel: ["Lead", "Intro Offer", "Membership / Pack", "Workshop Upsell", "Retention", "Revenue"],
  memberFunnel: ["Prospect", "Trial Class", "Member", "Workshop / Retreat", "Referral"],
  staffFunnel: ["Instructor", "Class Fill Rate", "Revenue"],
  marginTiers: { weak: "8 – 12%", average: "13 – 18%", strong: "19 – 25%" },
  startupItems: [
    { item: "Studio Buildout", percent: 30 },
    { item: "Lease & Deposits", percent: 28 },
    { item: "Marketing Launch", percent: 22 },
    { item: "Working Capital", percent: 20 },
  ],
  startupSideBySide: {
    equipment: "$15K – $40K",
    lease: "$20K – $55K",
    marketing: "$10K – $30K",
    total: "$50K – $150K",
  },
  valuation: {
    sde: "2.2× – 3.5×",
    revenue: "0.4× – 0.8×",
    ebitda: "3.0× – 5.0×",
    example: { revenue: "$450K", value: "$280K – $490K", note: "2.8× SDE on $130K SDE" },
  },
  scalingLadder: ["Single Studio", "100+ Active Members", "Workshop Revenue", "Multi-Studio Brand"],
  capitalEfficiency: {
    revenue: "$400K – $650K",
    profit: "$60K – $130K net profit",
    payback: "2 – 4 years",
  },
  recurringHighlight: {
    title: "Low-Capital Studio Model",
    value: "75 – 90% recurring revenue",
  },
};

export const martialArtsSchoolProfile: FitnessFormatProfile = {
  label: "Martial Arts School",
  kpis: {
    annualRevenue: "$300K – $850K",
    netMargin: "18 – 28%",
    ownerComp: "$75K – $150K",
    revenuePerMember: "$100 – $180/mo",
    startup: "$75K – $200K",
    valuation: "2.4× – 3.6× SDE",
    recurringPct: "70 – 85% MRR",
  },
  revenueSources: [
    "Monthly Tuition Programs",
    "Belt Testing & Graduation Fees",
    "Kids & Family Memberships",
    "Summer Camps & Seminars",
    "Retail (Uniforms & Gear)",
  ],
  revenueFunnel: ["Lead", "Trial Class", "Enrollment", "Belt Progression", "Retention", "Revenue"],
  memberFunnel: ["Prospect", "Trial Lesson", "Student", "Belt / Camp Upsell", "Family Referral"],
  staffFunnel: ["Student", "Attendance", "Revenue"],
  marginTiers: { weak: "10 – 14%", average: "15 – 20%", strong: "21 – 28%" },
  startupItems: [
    { item: "Mats & Equipment", percent: 25 },
    { item: "Lease & Buildout", percent: 30 },
    { item: "Marketing Launch", percent: 20 },
    { item: "Working Capital", percent: 25 },
  ],
  startupSideBySide: {
    equipment: "$20K – $55K",
    lease: "$25K – $65K",
    marketing: "$12K – $35K",
    total: "$75K – $200K",
  },
  valuation: {
    sde: "2.4× – 3.6×",
    revenue: "0.4× – 0.8×",
    ebitda: "3.2× – 5.2×",
    example: { revenue: "$550K", value: "$350K – $540K", note: "2.9× SDE on $150K SDE" },
  },
  scalingLadder: ["Single Dojo", "150+ Students", "Kids Program Focus", "Multi-Location School"],
  capitalEfficiency: {
    revenue: "$450K – $750K",
    profit: "$80K – $170K net profit",
    payback: "2 – 4 years",
  },
  recurringHighlight: {
    title: "Program-Based Recurring Revenue",
    value: "70 – 85% tuition MRR",
  },
};

export const danceStudioProfile: FitnessFormatProfile = {
  label: "Dance Studio",
  kpis: {
    annualRevenue: "$350K – $900K",
    netMargin: "16 – 26%",
    ownerComp: "$80K – $165K",
    revenuePerMember: "$95 – $175/mo",
    startup: "$70K – $220K",
    valuation: "2.2× – 3.4× SDE",
    recurringPct: "75 – 88% MRR",
  },
  revenueSources: [
    "Monthly Class Tuition",
    "Recital & Performance Fees",
    "Competition Team Programs",
    "Summer Camps & Intensives",
    "Costume & Merchandise Sales",
  ],
  revenueFunnel: ["Lead", "Trial Class", "Enrollment", "Recital Upsell", "Retention", "Revenue"],
  memberFunnel: ["Prospect", "Trial Lesson", "Student", "Competition / Recital", "Family Referral"],
  staffFunnel: ["Instructor", "Class Attendance", "Revenue"],
  marginTiers: { weak: "9 – 13%", average: "14 – 19%", strong: "20 – 26%" },
  startupItems: [
    { item: "Mirrors, Barres & Sound", percent: 28 },
    { item: "Lease & Buildout", percent: 32 },
    { item: "Marketing Launch", percent: 18 },
    { item: "Working Capital", percent: 22 },
  ],
  startupSideBySide: {
    equipment: "$18K – $55K",
    lease: "$22K – $70K",
    marketing: "$10K – $35K",
    total: "$70K – $220K",
  },
  valuation: {
    sde: "2.2× – 3.4×",
    revenue: "0.4× – 0.7×",
    ebitda: "3.0× – 4.8×",
    example: { revenue: "$620K", value: "$360K – $520K", note: "2.8× SDE on $145K SDE" },
  },
  scalingLadder: ["Single Studio", "180+ Students", "Competition Revenue", "Multi-Studio Brand"],
  capitalEfficiency: {
    revenue: "$500K – $800K",
    profit: "$80K – $165K net profit",
    payback: "2 – 4 years",
  },
  recurringHighlight: {
    title: "Tuition-Heavy Youth Model",
    value: "75 – 88% recurring tuition",
  },
};

export const swimSchoolProfile: FitnessFormatProfile = {
  label: "Swim School",
  kpis: {
    annualRevenue: "$400K – $1M",
    netMargin: "17 – 27%",
    ownerComp: "$90K – $180K",
    revenuePerMember: "$120 – $200/mo",
    startup: "$150K – $500K",
    valuation: "2.5× – 3.8× SDE",
    recurringPct: "80 – 92% MRR",
  },
  revenueSources: [
    "Monthly Lesson Memberships",
    "Group & Private Lesson Packages",
    "Swim Team Programs",
    "Summer Intensive Camps",
    "Lifeguard & Safety Certifications",
  ],
  revenueFunnel: ["Lead", "Assessment Lesson", "Enrollment", "Level Progression", "Retention", "Revenue"],
  memberFunnel: ["Prospect", "Trial Lesson", "Student", "Team / Camp Upsell", "Family Referral"],
  staffFunnel: ["Instructor", "Lesson Attendance", "Revenue"],
  marginTiers: { weak: "10 – 14%", average: "15 – 20%", strong: "21 – 27%" },
  startupItems: [
    { item: "Pool Access / Buildout", percent: 45 },
    { item: "Lease & Facility", percent: 22 },
    { item: "Marketing Launch", percent: 15 },
    { item: "Working Capital", percent: 18 },
  ],
  startupSideBySide: {
    equipment: "$60K – $200K",
    lease: "$35K – $120K",
    marketing: "$15K – $45K",
    total: "$150K – $500K",
  },
  valuation: {
    sde: "2.5× – 3.8×",
    revenue: "0.5× – 0.8×",
    ebitda: "3.4× – 5.2×",
    example: { revenue: "$720K", value: "$460K – $700K", note: "3.1× SDE on $190K SDE" },
  },
  scalingLadder: ["Single Pool Site", "200+ Active Students", "Team Program Revenue", "Multi-Location Operator"],
  capitalEfficiency: {
    revenue: "$600K – $950K",
    profit: "$100K – $200K net profit",
    payback: "3 – 5 years",
  },
  recurringHighlight: {
    title: "Lesson Package Recurring Model",
    value: "80 – 92% membership MRR",
  },
};

export const personalTrainingStudioProfile: FitnessFormatProfile = {
  label: "Personal Training Studio",
  kpis: {
    annualRevenue: "$250K – $650K",
    netMargin: "18 – 28%",
    ownerComp: "$90K – $175K",
    revenuePerMember: "$250 – $450/mo",
    startup: "$40K – $120K",
    valuation: "2.0× – 3.2× SDE",
    recurringPct: "55 – 75% MRR",
  },
  revenueSources: [
    "Personal Training Packages",
    "Semi-Private Sessions",
    "Small Group Training",
    "Online Coaching Programs",
    "Supplements & Apparel",
  ],
  revenueFunnel: ["Lead", "Consultation", "Package Sale", "Session Delivery", "Renewal", "Revenue"],
  memberFunnel: ["Prospect", "Assessment", "Client", "Package Renewal", "Referral"],
  staffFunnel: ["Trainer", "Session", "Revenue"],
  marginTiers: { weak: "10 – 14%", average: "15 – 20%", strong: "21 – 28%" },
  startupItems: [
    { item: "Equipment & Buildout", percent: 30 },
    { item: "Lease & Deposits", percent: 28 },
    { item: "Marketing Launch", percent: 22 },
    { item: "Working Capital", percent: 20 },
  ],
  startupSideBySide: {
    equipment: "$15K – $45K",
    lease: "$15K – $40K",
    marketing: "$8K – $25K",
    total: "$40K – $120K",
  },
  valuation: {
    sde: "2.0× – 3.2×",
    revenue: "0.3× – 0.6×",
    ebitda: "2.8× – 4.5×",
    example: { revenue: "$480K", value: "$240K – $400K", note: "2.6× SDE on $130K SDE" },
  },
  scalingLadder: ["Solo Trainer", "60+ Clients", "Hire Trainers", "Multi-Trainer Studio"],
  capitalEfficiency: {
    revenue: "$400K – $600K",
    profit: "$75K – $150K net profit",
    payback: "2 – 3 years",
  },
  recurringHighlight: {
    title: "Session-Package Model",
    value: "55 – 75% recurring packages",
  },
};

export const barreStudioProfile: FitnessFormatProfile = {
  label: "Barre Studio",
  kpis: {
    annualRevenue: "$300K – $750K",
    netMargin: "16 – 24%",
    ownerComp: "$75K – $145K",
    revenuePerMember: "$110 – $195/mo",
    startup: "$70K – $200K",
    valuation: "2.3× – 3.5× SDE",
    recurringPct: "80 – 92% MRR",
  },
  revenueSources: [
    "Monthly Unlimited Memberships",
    "Class Pack Sales",
    "Private & Semi-Private Sessions",
    "Workshops & Challenges",
    "Retail & Apparel",
  ],
  revenueFunnel: ["Lead", "Intro Offer", "Membership", "Class Upsell", "Retention", "Revenue"],
  memberFunnel: ["Prospect", "Intro Class", "Member", "Challenge / Workshop", "Referral"],
  staffFunnel: ["Instructor", "Class Fill Rate", "Revenue"],
  marginTiers: { weak: "9 – 13%", average: "14 – 19%", strong: "20 – 24%" },
  startupItems: [
    { item: "Barre Equipment & Mirrors", percent: 32 },
    { item: "Lease & Buildout", percent: 30 },
    { item: "Marketing Launch", percent: 18 },
    { item: "Working Capital", percent: 20 },
  ],
  startupSideBySide: {
    equipment: "$25K – $70K",
    lease: "$22K – $60K",
    marketing: "$10K – $35K",
    total: "$70K – $200K",
  },
  valuation: {
    sde: "2.3× – 3.5×",
    revenue: "0.4× – 0.8×",
    ebitda: "3.2× – 5.0×",
    example: { revenue: "$520K", value: "$310K – $480K", note: "2.8× SDE on $140K SDE" },
  },
  scalingLadder: ["Single Studio", "120+ Members", "Challenge Revenue", "Multi-Studio Brand"],
  capitalEfficiency: {
    revenue: "$450K – $700K",
    profit: "$70K – $150K net profit",
    payback: "2 – 4 years",
  },
  recurringHighlight: {
    title: "Membership-Heavy Model",
    value: "80 – 92% recurring revenue",
  },
};
