/** Shared directional anchors for hair salon franchise ranking reports (2025–2026). */

export const franchiseAnchors = {
  investmentLow: "$140K",
  investmentMedian: "$225K",
  investmentHigh: "$400K",
  franchiseFee: "$20K – $50K",
  royalty: "6% + 2–5% ads",
  royaltyCombined: "6 – 12%",
  unitRevenue: "$300K – $700K",
  medianRevenue: "$450K",
  netMarginAfterFees: "6 – 12%",
  ebitda: "8 – 16%",
  ownerIncomeSingle: "$45K – $110K",
  ownerIncomeMulti: "$150K – $350K",
  payback: "3 – 5 years",
  averageTicket: "$22 – $45",
} as const;

export const franchiseRankingSources = [
  "Franchise Disclosure Document (FDD) Item 5–7 ranges (brand systems)",
  "BizMetricsHQ salon franchise operator panel (directional)",
  "Public franchise directories and unit-count disclosures",
  "U.S. hair salon industry benchmarks 2025–2026",
] as const;

/** Brand rows reused across rankings — criteria-specific sorts live in each report. */
export const brandEconomics = {
  greatClips: {
    name: "Great Clips",
    investment: "$150K – $350K",
    fee: "$20K – $45K",
    royalty: "6% + ads",
    units: "4,000+",
    revenue: "$380K – $650K",
    netMargin: "7 – 12%",
    growth: "High",
    firstTimerFit: "Excellent",
    notes: "Largest footprint; app-driven traffic; multi-unit friendly",
  },
  supercuts: {
    name: "Supercuts",
    investment: "$160K – $340K",
    fee: "$30K – $40K",
    royalty: "6% + ads",
    units: "2,000+",
    revenue: "$350K – $600K",
    netMargin: "6 – 11%",
    growth: "Moderate",
    firstTimerFit: "Strong",
    notes: "Family value positioning; established mall/plaza presence",
  },
  sportClips: {
    name: "Sport Clips",
    investment: "$250K – $400K",
    fee: "$30K – $50K",
    royalty: "6% + ads",
    units: "1,800+",
    revenue: "$420K – $700K",
    netMargin: "7 – 13%",
    growth: "High",
    firstTimerFit: "Strong",
    notes: "Men’s niche; higher typical build; strong brand loyalty",
  },
  fantasticSams: {
    name: "Fantastic Sams",
    investment: "$170K – $320K",
    fee: "$25K – $40K",
    royalty: "6% + ads",
    units: "900+",
    revenue: "$320K – $550K",
    netMargin: "6 – 11%",
    growth: "Moderate",
    firstTimerFit: "Excellent",
    notes: "Full-service neighborhood model; training depth",
  },
  costCutters: {
    name: "Cost Cutters",
    investment: "$140K – $300K",
    fee: "$20K – $35K",
    royalty: "6% + ads",
    units: "500+",
    revenue: "$300K – $520K",
    netMargin: "6 – 11%",
    growth: "Moderate",
    firstTimerFit: "Good",
    notes: "Often lowest total investment band among national systems",
  },
  regis: {
    name: "Regis (brand portfolio)",
    investment: "$180K – $380K",
    fee: "$25K – $45K",
    royalty: "6% + ads",
    units: "Portfolio",
    revenue: "$340K – $620K",
    netMargin: "6 – 10%",
    growth: "Selective",
    firstTimerFit: "Moderate",
    notes: "Mall/chain formats; brand-dependent economics",
  },
  drybar: {
    name: "Drybar",
    investment: "$300K – $550K+",
    fee: "$40K – $60K",
    royalty: "7% + ads",
    units: "Growing",
    revenue: "$450K – $850K",
    netMargin: "5 – 10%",
    growth: "High (selective markets)",
    firstTimerFit: "Moderate",
    notes: "Premium blowout niche; higher CapEx; strong brand traffic",
  },
  blo: {
    name: "Blo Blow Dry Bar",
    investment: "$250K – $450K",
    fee: "$35K – $50K",
    royalty: "6–7% + ads",
    units: "Growing",
    revenue: "$400K – $750K",
    netMargin: "5 – 11%",
    growth: "High",
    firstTimerFit: "Good",
    notes: "Blow-dry specialty; urban/suburban densification opportunity",
  },
} as const;

export const guideLinks = {
  hub: "/franchise/beauty/hair-salon/",
  compare: "/franchise/beauty/hair-salon/#compare-brands",
  economics: "/franchise/beauty/hair-salon/#economics",
  startup: "/franchise/beauty/hair-salon/#startup-costs",
  vsIndependent: "/comparisons/hair-salon-vs-franchise-salon/",
  startupCalc: "/calculators/hair-salon-startup-cost/",
  breakEvenCalc: "/calculators/hair-salon-break-even/",
  marginCalc: "/calculators/hair-salon-profit-margin/",
  valuationCalc: "/calculators/hair-salon-valuation/",
} as const;
