import { buildAllFranchiseRankings, type FranchiseRankingIndustryConfig } from "../build-franchise-rankings";

const sources = [
  "Franchise Disclosure Document (FDD) Item 5–7 ranges (brand systems)",
  "BizMetricsHQ medical spa / aesthetic franchise operator panel (directional)",
  "Public franchise directories and unit-count disclosures",
  "U.S. medical spa industry benchmarks 2025–2026",
] as const;

const config: FranchiseRankingIndustryConfig = {
  industryKey: "medical-spa",
  industryLabel: "Medical Spa",
  industryLabelPlural: "Medical Spas",
  noun: "medical spa",
  guideHref: "/franchise/beauty/medical-spa/",
  rankingsBaseHref: "/franchise/beauty/medical-spa/rankings/",
  sources,
  anchors: {
    investmentRange: "$350K – $1.2M+",
    medianInvestment: "$650K",
    franchiseFee: "$35K – $75K",
    royaltyCombined: "6 – 12%",
    unitRevenue: "$800K – $3M+",
    medianRevenue: "$1.5M",
    netMarginAfterFees: "10 – 20%",
    ebitda: "12 – 25%",
    ownerIncomeSingle: "$100K – $220K",
    payback: "3 – 6 years",
  },
  calculators: [
    { label: "Medical Spa Startup Cost Calculator", href: "/calculators/medical-spa-startup-cost/" },
    { label: "Medical Spa Profit Margin Calculator", href: "/calculators/medical-spa-profit-margin/" },
    { label: "Medical Spa Valuation Calculator", href: "/calculators/medical-spa-valuation/" },
  ],
  compareHref: "/comparisons/medical-spa-vs-day-spa/",
  keywords: {
    best: ["best medical spa franchises", "best med spa franchise to buy", "top medical spa franchise opportunities"],
    "lowest-cost": ["lowest cost medical spa franchise", "cheapest med spa franchise", "medical spa franchise under 500k"],
    "highest-revenue": ["highest revenue medical spa franchise", "how much does a med spa franchise make", "med spa franchise average sales"],
    "fastest-growing": ["fastest growing medical spa franchises", "med spa franchise expansion 2026", "growing laser clinic franchises"],
    "first-time": ["best medical spa franchise for first-time owners", "med spa franchise for beginners", "medical spa franchise no experience"],
    "most-profitable": ["most profitable medical spa franchise", "highest ROI med spa franchise", "medical spa franchise profit margin"],
  },
  brands: [
    {
      name: "Milan Laser",
      investment: "$450K – $900K",
      fee: "$45K – $60K",
      royalty: "6% + ads",
      units: "300+",
      revenue: "$1.0M – $2.2M",
      netMargin: "12 – 20%",
      growth: "High",
      firstTimerFit: "Excellent",
      notes: "Laser-first focus; strong package volume and multi-unit density",
      costRank: 3,
      revenueRank: 2,
      growthRank: 1,
      firstTimerRank: 1,
      profitRank: 1,
      bestRank: 1,
      buyerFit: "Laser clinic multi-unit",
    },
    {
      name: "Ideal Image",
      investment: "$500K – $1.1M",
      fee: "$40K – $60K",
      royalty: "6% + ads",
      units: "150+",
      revenue: "$1.2M – $2.8M",
      netMargin: "11 – 19%",
      growth: "High",
      firstTimerFit: "Strong",
      notes: "Broad aesthetic menu; strong national consumer awareness",
      costRank: 5,
      revenueRank: 1,
      growthRank: 2,
      firstTimerRank: 3,
      profitRank: 2,
      bestRank: 2,
      buyerFit: "Full med spa operators",
    },
    {
      name: "LaserAway",
      investment: "$400K – $850K",
      fee: "$40K – $55K",
      royalty: "6% + ads",
      units: "100+",
      revenue: "$900K – $2.0M",
      netMargin: "11 – 18%",
      growth: "High",
      firstTimerFit: "Strong",
      notes: "Urban laser clinics; brand-driven patient acquisition",
      costRank: 2,
      revenueRank: 4,
      growthRank: 3,
      firstTimerRank: 2,
      profitRank: 3,
      bestRank: 3,
      buyerFit: "Urban laser buyers",
    },
    {
      name: "Face Foundrie",
      investment: "$350K – $650K",
      fee: "$35K – $50K",
      royalty: "6% + ads",
      units: "Growing",
      revenue: "$700K – $1.4M",
      netMargin: "10 – 17%",
      growth: "High",
      firstTimerFit: "Good",
      notes: "Express facial aesthetics; often lower CapEx entry",
      costRank: 1,
      revenueRank: 6,
      growthRank: 4,
      firstTimerRank: 4,
      profitRank: 4,
      bestRank: 4,
      buyerFit: "Capital-constrained aesthetic",
    },
    {
      name: "SEV Laser",
      investment: "$400K – $800K",
      fee: "$40K – $55K",
      royalty: "6% + ads",
      units: "Growing",
      revenue: "$850K – $1.8M",
      netMargin: "10 – 18%",
      growth: "High",
      firstTimerFit: "Good",
      notes: "Laser-first clinic model with expansion momentum",
      costRank: 4,
      revenueRank: 5,
      growthRank: 5,
      firstTimerRank: 5,
      profitRank: 5,
      bestRank: 5,
      buyerFit: "Laser-focused owners",
    },
    {
      name: "Sono Bello",
      investment: "$600K – $1.2M+",
      fee: "$50K – $75K",
      royalty: "Varies + ads",
      units: "70+",
      revenue: "$1.5M – $3.5M+",
      netMargin: "8 – 16%",
      growth: "Selective",
      firstTimerFit: "Moderate",
      notes: "Highest revenue ceiling; heavier CapEx and clinical complexity",
      costRank: 6,
      revenueRank: 3,
      growthRank: 6,
      firstTimerRank: 6,
      profitRank: 6,
      bestRank: 6,
      buyerFit: "Body contour / higher acuity",
    },
  ],
};

const built = buildAllFranchiseRankings(config);

export const medicalSpaFranchiseRankings = built.bySlug;
export const medicalSpaFranchiseRankingSlugs = built.slugs;
export const medicalSpaFranchiseRankingCards = built.cards;
